- name: Ansible Analogue Pocket
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:
    - name: execute_latest_firmware_role
      prompt: Include [ Latest Firmware ]?
      private: false
      default: "yes"

    - name: execute_openfpga_cores_role
      prompt: Include [ OpenFPGA Cores ]?
      private: false
      default: "yes"

    - name: execute_retrodriven_assets_role
      prompt: Include [ RetroDriven Assets ]?
      private: false
      default: "yes"

    - name: execute_megazxretro_platform_art_role
      prompt: Include [ MegaZXretro Platform Art ]?
      private: false
      default: "yes"

    - name: execute_spiritualized1997_library_image_set_role
      prompt: Include [ spiritualized1997 Library Image Set ]?
      private: false
      default: "yes"

  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: vars

    - name: Initialize
      ansible.builtin.include_tasks: tasks/init.yml

    - name: Cleanup
      ansible.builtin.include_tasks: tasks/cleanup.yml
      when: >-
        (execute_latest_firmware_role | bool)
        or
        (execute_openfpga_cores_role | bool)
        or
        (execute_retrodriven_assets_role | bool)
        or
        (execute_megazxretro_platform_art_role | bool)
        or
        (execute_spiritualized1997_library_image_set_role | bool)

    ###

    - name: Check 'Latest Firmware'
      ansible.builtin.include_role:
        name: latest_firmware
      when: execute_latest_firmware_role | bool

    - name: Process 'OpenFPGA Cores'
      ansible.builtin.include_role:
        name: openfpga_cores
      when: execute_openfpga_cores_role | bool

    - name: Get assets from 'RetroDriven'
      ansible.builtin.include_role:
        name: retrodriven_assets
      when: execute_retrodriven_assets_role | bool

    - name: Get platform art from 'MegaZXretro'
      ansible.builtin.include_role:
        name: megazxretro_platform_art
      when: execute_megazxretro_platform_art_role | bool

    - name: Get library image set from 'spiritualized1997'
      ansible.builtin.include_role:
        name: spiritualized1997_library_image_set
      when: execute_spiritualized1997_library_image_set_role | bool

    ###

    - name: Merge
      ansible.builtin.include_tasks: tasks/merge.yml

    ###

    - name: Remove 'JTBETA' Cores
      ansible.builtin.include_tasks: tasks/remove_jt_beta_cores/main.yml
      when:
        - execute_openfpga_cores_role | bool
        - remove_jt_beta_cores | default(false)

    - name: Rename 'jt' Cores
      ansible.builtin.include_tasks: tasks/rename_jt_cores/main.yml
      when:
        - execute_openfpga_cores_role | bool
        - rename_jt_cores | default(false)

    ###

    - name: Set custom core names
      ansible.builtin.include_tasks: tasks/custom_core_name.yml
      loop: "{{ custom_core_names | dict2items }}"
      loop_control:
        label: "{{ custom_core_name.key }}"
        loop_var: custom_core_name
      when:
        - custom_core_names is defined
        - (custom_core_names | length) > 0
